#端口
server:
  port: 8888


spring:
  #数据库配置
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://120.79.252.252:3306/db_job?useUnicode=true&allowMultiQueries=true&useSSL=false&characterEncoding=utf-8
    username: root
    password: 1234
    tomcat:
      max-active: 10
      max-idle: 5
      min-idle: 5
  #redis
  redis:
    host: 120.79.252.252
    pool:
      max-active: 200
      max-wait: 5000
      max-idle: 150
      min-idle: 0

    timeout: 6000

  #rabbitmq配置
  rabbitmq:
    host: 120.79.252.252
    port: 5672
    username: guest
    password: guest
    #消息发送到交换机确认机制,是否确认回调
    publisher-confirms: true
    #消息发送到队列确认机制，是否确认回调
    publisher-returns: true
    #手动确认消息
    listener:
      simple:
        acknowledge-mode: manual
#交换机
job:
  exchange:
    seeker: seeker
    recruiter: recruiter

#mybatis
mybatis:
  type-aliases-package: com.yyh.job.dao.model
  mapper-locations: classpath*:mappers/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

#分页插件
pagehelper:
  reasonable: false
  helper-dialect: mysql
  support-methods-arguments: true
  params: count=countSql

#七牛云服务
qiniu:
  bucket: job_bucket
  secretKey: QuVitoseWoGsZedMV2KUIsLz_ruew8PvCvXqH4lU
  accessKey: YI609XuwI9gp-o6DZnVhEfGPSf-cGWHJIo8S-ASj
  urlPrefix: http://image.yangyhao.top/
