#端口
server:
  port: 8888


spring:
  #数据库配置
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://rm-bp1908u6a7tofk507ko.mysql.rds.aliyuncs.com:3306/db_job?useUnicode=true&allowMultiQueries=true&useSSL=false&characterEncoding=utf-8
    username: root
    password: aiYYH!1314
    tomcat:
      max-active: 10
      max-idle: 5
      min-idle: 5
  #redis
  redis:
    host: 120.79.252.252
    pool:
      max-active: 200
      max-wait: 5000
      max-idle: 150
      min-idle: 0

    timeout: 6000


#mybatis
mybatis:
  type-aliases-package: com.yyh.job.dao.model
  mapper-locations: classpath*:mappers/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

#分页插件
pagehelper:
  reasonable: false
  helper-dialect: mysql
  support-methods-arguments: true
  params: count=countSql


#七牛云服务
qiniu:
  bucket: job_bucket
  secretKey: QuVitoseWoGsZedMV2KUIsLz_ruew8PvCvXqH4lU
  accessKey: YI609XuwI9gp-o6DZnVhEfGPSf-cGWHJIo8S-ASj
  urlPrefix: http://image.yangyhao.top/
